---
type: object
additionalProperties: false
patternProperties:
  "^[a-zA-Z][_\\-a-zA-Z]*$":
    type: object
    oneOf:
    - type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
      additionalProperties: false
    - type: object
      properties:
        token:
          type: string
      required:
        - token
      additionalProperties: false
    - type: object
      properties:
        apikey:
          type: string
      required:
        - apikey
      additionalProperties: false